baseURL = "https://romanskii.github.io/"

relativeURLs = true
canonifyURLs = false

languageCode = "uk-UA"
title = "Система автоматизованого розгортання"

[params]
author = "Студент"
description = "Демонстраційний вебпроєкт для дипломної роботи"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true